name: HelloWorkFlow

on: [push]
jobs:
   Hello:
      runs-on: ubuntu-latest
      steps:
         - name: Show message
           run: echo "HelloWorkflow"
         - name: Checkout
           uses: actions/checkout@v4
         - name: ListDir
           run: ls -alh
         - name: make file 
           run: touch fruits.txt
         - name : Add data
           run : echo "orange","apple","banana","mango","apple","mango" > fruits.txt
         - name : make file for excute sorting
           run : touch run.sh
         - name : add Excution command
           run :  sort $1 | uniq -c | awk -F' ' '{print $2 " --> "$1}' > group.txt
           run :  cat group.txt
         - name: run file
           run : ./run.sh fruits.txt
         - name: SetupPython
           uses: actions/setup-python@v5
           with:
                python-version: "3.10"
         - name: CheckPythonVersion
           run: python --version
         - name: RunPython
           run: python app.py
        
